[versions]
plugin-android = "7.2.1"
plugin-kotlin = "1.6.10"
plugin-detekt = "1.20.0"
plugin-fataar = "1.3.8"

androidx-core = "1.8.0"
androidx-appcompat = "1.4.2"
activity-compose = "1.4.0"
androidx-lifecycle = "2.4.1"
androidx-fragment = "1.4.1"
androidx-datastore = "1.0.0"

compose-version = "1.1.1"
compose-navigation = "2.4.2"
material = "1.6.1"
material3 = "1.0.0-alpha13"

navigation = "2.4.2"
viewbinding = "1.5.6"

kotlinx-coroutines = "1.6.1"
koin = "3.2.0"
timber = "5.0.1"
gson = "2.9.0"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "plugin-kotlin" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "plugin-detekt" }
plugin-fataar = { module = "com.github.kezong:fat-aar", version.ref = "plugin-fataar" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-composeactivity = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-lifecyclektx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-version" }
compose-uitooling = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-version" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

viewbinding = { module = "com.github.kirich1409:viewbindingpropertydelegate", version.ref = "viewbinding" }

[bundles]
plugins = ["plugin-android", "plugin-kotlin", "plugin-detekt", "plugin-fataar"]